
services:
    vectordb:
        image: semitechnologies/weaviate:1.31.4-2ce3a66
        ports:
        - "8080:8080"
        - "50051:50051"
        volumes:
        - weaviate_data:/var/lib/weaviate
        restart: on-failure:0
        environment:
          QUERY_DEFAULTS_LIMIT: 25
          AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
          PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
          ENABLE_API_BASED_MODULES: 'true'
          CLUSTER_HOSTNAME: 'node1'
    db:
        image: postgres:15.13
        ports:
        - "5432:5432"
        volumes:
        - postgres_data:/var/lib/postgres/data
volumes:
  weaviate_data:
